AzpPj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', include('info.urls')),
    # path('', include('info.urls')),

]

info/urls.py
from django.contrib import admin
from django.urls import path
from info import views

app_name = 'info'
urlpatterns = [
    path('', views.index,name='index'),
    path('groups',views.groups,name='groups'),
    path('add',views.add,name='add'),
    path('creategroup',views.creategroup,name='creategroup'),
    path('post',views.post,name='post'),
    path('good/<int:good_id>',views.good,name='good'),
]

info/models.py
import re
from statistics import mode
from django.db import models
from django.contrib.auth.models import User

class Message(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE,related_name='message_owner')
    group = models.ForeignKey('Group',on_delete=models.CASCADE)
    content = models.TextField(max_length=1000)
    good_count = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.content) + '('+ str(self.owner)+')'

    class Meta:
        ordering = ('-pub_date',) #-つけることでpub_dateを新しい順にする

class Group(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE,related_name='group_owner')
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Employee(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE,related_name='employee_owner')
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    group = models.ForeignKey(Group,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user) + '(group:"'+ str(self.group)+'")'

class Good(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE,related_name='good_owner')
    message = models.ForeignKey(Message,on_delete=models.CASCADE)

    def __str__(self) :
        return 'LGTM for"'+str(self.message)+'"(by'+ str(self.owner)+')'

info/forms.py
from attr import field
from django import forms

from.models import Message,Group,Employee,Good
from django.contrib.auth.models import User


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['owner','group','content']

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['owner','title']

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['owner','group','user']

class GoodForm(forms.ModelForm):
    class Meta:
        model = Good
        fields = ['owner','message']

class SearchForm(forms.Form):
    search = forms.CharField(max_length=100)

class GroupCheckForm(forms.Form):
    def __init__(self,user,*args,**kwargs):
        super(GroupCheckForm,self).__init__(*args,**kwargs)
        public = User.objects.filter(username='public').first()
        self.fields['groups'] = forms.MultipleChoiceField(
            choices=[(item.title,item.title)
            for item in Group.objects.filter(owner__in=[user,public])],
            widget=forms.CheckboxSelectMultiple(),
        )

class GroupSelectForm(forms.Form):
    def __init__(self,user,*args,**kwargs):
        super(GroupSelectForm,self).__init__(*args,**kwargs)
        self.fields['groups'] = forms.ChoiceField(
            choices=[('-','-')] + [(item.title,item.title) 
            for item in Group.objects.filter(owner=user)],
        )

class EmployeesForm(forms.Form):
    def __init__(self,user,employees =[],vals =[],*args,**kwargs):
        super(EmployeesForm,self).__init__(*args,**kwargs)
        public = User.objects.filter(username='public').first()
        self.fields['employees'] = forms.MultipleChoiceField(
            choices=[(item.user,item.user) for item in employees],
            widget=forms.CheckboxSelectMultiple(),
            initial=vals
        )

class CreateGroupForm(forms.Form):
    group_name = forms.CharField(max_length=50)

class PostForm(forms.Form):
    content = forms.CharField(max_length=500,widget=forms.Textarea)
    def __init__(self,user,*args,**kwargs):
        super(PostForm,self).__init__(*args,**kwargs)
        public = User.objects.filter(username='public').first()
        self.fields['groups'] = forms.ChoiceField(
            choices=[('-','-')] + [(item.title,item.title)
            for item in Group.objects.filter(owner__in=[user,public])],
        )

info/views.py
import re
from tabnanny import check

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import redirect, render
# from requests import request

from info.models import Employee, Good, Group, Message

from .forms import (CreateGroupForm, EmployeesForm, GroupCheckForm,
                    GroupSelectForm, PostForm, SearchForm)

@login_required(login_url='/admin/login/')
def index(request):
    (public_user,public_group) = get_public()

    if request.method == 'POST':

        if request.POST['mode'] == '__check_form__':
            searchform = SearchForm()
            checkform = GroupCheckForm(request.user,request.POST)

            glist = []
            for item in request.POST.getlist('groups'):
                glist.append(item)
            messages = get_your_group_message(request.user,glist,None)

        if request.POST['mode'] == '__search_form__':
            searchform = SearchForm(request.POST)
            checkform = GroupCheckForm(request.user)

            gps = Group.objects.filter(owner=request.user)
            glist = [public_group]
            for item in gps:
                glist.append(item)
            messages = get_your_group_message(request.user,glist,request.POST['search'])

    else:
        searchform = SearchForm()
        checkform = GroupCheckForm(request.user)
        
        gps = Group.objects.filter(owner=request.user)
        glist = [public_group]
        for item in gps:
            glist.append(item)
        messages = get_your_group_message(request.user,glist,None)

    params = {
        'login_user':request.user,
        'contents':messages,
        'check_form':checkform,
        'search_form':searchform,
    }
    print(glist)
    return render(request,'info/index.html',params)

@login_required(login_url='/admin/login/')
def groups(request):
    employees = Employee.objects.filter(owner=request.user)
    if request.method == 'POST':
        if request.POST['mode'] == '__groups_form__':
            sel_group = request.POST['groups']
            gp = Group.objects.filter(owner=request.user).filter(title=sel_group).first()
            fds = Employee.objects.filter(owner=request.user).filter(group=gp)
            vlist=[]
            for item in fds:
                vlist.append(item.user.username)
                groupsform = GroupSelectForm(request.user,request.POST)
                employeesform = EmployeesForm(request.user,employees=employees,vals=vlist)

        if request.POST['mode'] == '__employees_form__':
            sel_group = request.POST['group']
            group_obj = Group.objects.filter(title=sel_group).first()
            sel_fds = request.POST.getlist('employee')
            sel_users = User.objects.filter(username__in=sel_fds)
            fds = Employee.objects.filter(owner=request.user).filter(user__in=sel_users)
            vlist=[]
            for item in fds:
                item.group = group_obj
                item.save()
                vlist.append(item.user.username)
            messages.success(request,'☑されたユーザーを'+sel_group+'に登録済み')
            groupsform = GroupSelectForm(request.user,{'groups':sel_group})
            employeesform = EmployeesForm(request.user,employees=employees,vals=vlist)
        #GETアクセス時
    else:
        groupsform = GroupSelectForm(request.user)
        employeesform = EmployeesForm(request.user,employees=employees,vals=[])
        sel_group = '-'
    createform = CreateGroupForm()
    params = {
        'login_user':request.user,
        'groups_form':groupsform,
        'employees_form':employeesform,
        'create_form':createform,
        'group':sel_group,
    }
    return render(request,'info/groups.html',params)

#追加
@login_required(login_url='/admin/login')
def add(request):
    add_name = request.GET['name']
    add_user = User.objects.filter(username=add_name).first()
    if add_user == request.user:
        messages.info(request,"自分自身を追加することはできません")
        return redirect(to='/info')
    (public_user,public_group) = get_public()
    frd_num = Employee.objects.filter(owner=request.user).filter(user=add_user).count()
    if frd_num > 0:
        messages.info(request,add_user.username+'は追加済み')
        return redirect(to='/info')
    frd = Employee()
    frd.owner = request.user
    frd.user = add_user
    frd.group = public_group
    frd.save()
    messages.success(request,add_user.username + 'を追加しました！追加したユーザーをメンバーに設定する場合、Groupに移動してください')
    return redirect(to='/info')

#グループ作成
@login_required(login_url='/admin/login/')
def creategroup(request):
    gp = Group()
    gp.owner = request.user
    gp.title = request.POST['group_name']
    gp.save()
    messages.info(request,'新しいグループを作成しました！')
    return redirect(to='/info/groups')

#投稿
@login_required(login_url='/admin/login/')
def post(request):

    if request.method == 'POST':
        gr_name = request.POST['groups']
        content = request.POST['content']
        group = Group.objects.filter(owner=request.user).filter(title=gr_name).first()
        if group == None:
            (pub_user,group) = get_public()
        msg = Message()
        msg.owner = request.user
        msg.group = group
        msg.content = content
        msg.save()

        messages.success(request,'投稿しました！')
        return redirect(to='/info')

    else:
        form = PostForm(request.user)
    params = {
        'login_user':request.user,
        'form':form,
    }
    return render(request,'info/post.html',params)

#ふぁぼ
@login_required(login_url='/admin/login/')
def good(request,good_id):
    good_msg = Message.objects.get(id=good_id)
    is_good = Good.objects.filter(owner=request.user).filter(message=good_msg).count()
    if is_good > 0:
        messages.success(request,'It was successful!')
        return redirect(to='/info')
    good_msg.good_count += 1
    good_msg.save()
    good = Good()
    good.owner = request.user
    good.message = good_msg
    good.save()

    messages.success(request,'LGTM♡')
    return redirect(to='/info')

def get_your_group_message(owner,glist,find):
    (public_user,public_group) = get_public()
    groups = Group.objects.filter(Q(owner=owner)|Q(owner=public_user)).filter(title__in=glist)
    me_employees = Employee.objects.filter(group__in=groups)
    me_users = []
    for f in me_employees:
        me_users.append(f.user)
    his_groups = Group.objects.filter(owner__in=me_users)
    his_employees = Employee.objects.filter(user=owner).filter(group__in=his_groups)
    me_groups = []
    for hf in his_employees:
        me_employees.append(hf.group)
    if find == None:
        messages = Message.objects.filter(Q(group__in=groups)|Q(group__in=me_groups))[:100]
    else:
        messages = Message.objects.filter(Q(group__in=groups)|Q(group__in=me_groups)).filter(content__contains=find)[:100]
        return messages

def get_public():
    public_user = User.objects.filter(username='public').first()
    public_group = Group.objects.filter(owner=public_user).first()

    return (public_user,public_group)

info/templates/info/groups.html
{% extends 'info/layout.html' %}
{% block title %}groups{% endblock %}
{% block header %}
<h1>グループ</h1>
<p class="caption">※グループを選択してselect memberすると、そのグループに登録されている利用者がONになります。
    利用者のチェックをONにしてset memberすると、ONの利用者がグループに追加されます。
</p>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<form action="{% url 'info:groups' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="mode" value="__groups_form__">
    {{groups_form}}
    <button>select members</button>
</form>

<hr>
<form action="{% url 'info:groups' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="mode" value="__employees_form__">
    <input type="hidden" name="group" value="{{group}}">
    {{employees_form}}
    <button>set members</button>
</form>

<hr>
<p>※新しいグループの登録</p>
<form action="{% url 'info:creategroup' %}" method="post">
    {% csrf_token %}
    {{create_form}}
    <button>create new group</button>
</form>
{% endblock %}

info/templates/info/index.html
{% extends 'info/layout.html' %}
{% block title %}index{% endblock %}
{% block header %}
<h1>info</h1>
<p class="caption">※グループのチェックをONにして更新すると、グループに登録されてるユーザーのメッセージだけを表示します。</p>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if messages.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<form action="{% url 'info:index' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="mode" value="__search_form__">
    {{ search_form }}
    <button>Search</button>
</form>
<hr>
<form actinon="{% url 'info:index' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="mode" value="__check_form__">
    {{ check_form }}
    <button>update</button>
</form>
{% for item in contents %}
<hr>
<p class="message_public">
    {% if item.group.title == 'public' %}
    [public]
    {% endif %}
</p>
    <p class="message_content">{{ item.content }}</p>
    <p class="message_date">({{ item.pub_date }})</p>

    <p class="message_owner">
        <span class="message_counter">LGTM : {{item.good_count}}</span>
        "{{item.owner}}"(<a href="{% url 'info:add' %}?name={{item.owner}}">ユーザー追加</a>)
        <a href="{% url 'info:good' item.id %}"><button>LGTM！</button></a>
    </p>
{% endfor %}
{% endblock %}

info/templates/info/layout.html
{% load static %}
<!doctype html>
<html lang ="ja">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            {% endblock %}
        </title>
        <link rel="stylesheet" type="text/css" href="{% static './css/style.css' %}" />
    </head>
    <body>
        <div class="body_content">
            <div class="body_content_inner">
                <table class="login_table" width="100%">
                    <tr><th width="150px">menu</th><td>
                        <table class="login_table_inner">
                            <tr>
                                <td><a href="{% url 'info:index' %}">top</a></td>
                                <td><a href="{% url 'info:post' %}">投稿</a></td>
                                <td><a href="{% url 'info:groups' %}">group</a></td>
                            </tr>
                        </table>
                    </td>
                    </tr>
                    <tr><th width="150px">login user:</th>
                    <td>"{{login_user}}"</td></tr>
                </table>
                <div class="header">{% block header %}{% endblock %}</div>
                <div class="content">{% block content %}{% endblock %}</div>
                <div class="footer">
                    <hr>
                    <div >
                        <span style="float:left;font-weight:bold;">
                        <a href="/admin/logout?next=/info/">[ logout ]</a></span>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

info/templates/info/post.html
{% extends 'info/layout.html' %}
{% block title %}post{% endblock %}
{% block header %}
<h1>投稿</h1>
<p class="caption">※投稿先のグループを選択し、メッセージを投稿します。</p>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{message.tags}}"
    {% endif %}>{{message}}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}

<form action="{% url 'info:post' %}" method="post">

    {% csrf_token %}
    <table>
        {{form.as_table}}
        <tr><td></td><td><button">投稿</button></td></tr>
    </table>
</form>
{% endblock %}